from typing import Any

MANUAL_PRACTICE: dict[int, list[dict[str, Any]]] = {
    87: [{'title': 'Добавьте Category и настоящий foreign key',
       'task': 'Расширьте database schema отношением one-to-many. SQLite должен реально проверять foreign key, а не '
               'только хранить integer.',
       'steps': ['Создайте модель Category с id и уникальным name.',
                 'Добавьте Task.category_id как nullable foreign key на categories.id.',
                 'Для SQLite включите PRAGMA foreign_keys=ON через SQLAlchemy event listener при connect.',
                 'На disposable database пересоздайте schema через create_all.',
                 'Создайте category и две tasks с её category_id.',
                 'Создайте Task с несуществующим category_id.',
                 'Поймайте IntegrityError, выполните rollback и верните HTTP 409 либо 422 по зафиксированному '
                 'контракту.',
                 'Добавьте GET /categories/{category_id}/tasks.',
                 'Проверьте существующую category, пустую category и неизвестный category_id.',
                 'Добавьте tests для valid foreign key и invalid foreign key.'],
       'result': 'Готово, если одна Category связана с несколькими Task, SQLite отклоняет несуществующий '
                 'category_id, а API различает пустую и отсутствующую category.'}],
    88: [{'title': 'Настройте relationship в обе стороны',
       'task': 'Добавьте ORM-навигацию Category.tasks и Task.category поверх уже работающего foreign key.',
       'steps': ["В Category объявите tasks: Mapped[list['Task']] через relationship(back_populates='category').",
                 "В Task объявите category: Mapped['Category | None'] через relationship(back_populates='tasks').",
                 'Не удаляйте category_id: relationship не заменяет foreign key.',
                 'Создайте Category и Task через task.category = category.',
                 'Выполните add, commit и refresh.',
                 'В новой Session загрузите Task и проверьте task.category.name.',
                 'Загрузите Category и проверьте заголовки category.tasks.',
                 'Добавьте Pydantic response schema, которая не создаёт бесконечную рекурсию Category → Task → '
                 'Category.',
                 'Добавьте тест, что assignment relationship заполняет category_id после flush или commit.'],
       'result': 'Готово, если обе стороны relationship согласованы с category_id, создание через Python-object '
                 'работает, а response schema не зацикливается.'}],
    89: [{'title': 'Докажите и устраните N+1',
       'task': 'Сравните два способа загрузки Category вместе с tasks по фактическому числу SQL-запросов.',
       'steps': ['Создайте минимум три categories, у каждой должно быть не меньше двух tasks.',
                 'Включите SQL echo либо тестовый query counter через SQLAlchemy event before_cursor_execute.',
                 'Выполните select(Category), затем в цикле обратитесь к category.tasks.',
                 'Запишите число queries: один для categories и дополнительные запросы для связей.',
                 'Создайте второй statement с selectinload(Category.tasks).',
                 'Повторите тот же response и снова посчитайте queries.',
                 'Проверьте, что JSON обоих вариантов совпадает.',
                 'Зафиксируйте ожидаемую границу: selectin-вариант использует два основных SELECT независимо от '
                 'числа categories.',
                 'Добавьте regression test на верхнюю границу query count.'],
       'result': 'Готово, если N+1 подтверждён измерением, selectinload сохраняет response, а test не позволяет '
                 'случайно вернуть отдельный query для каждой Category.'}],
    90: [{'title': 'Создайте первую воспроизводимую migration',
       'task': 'Подключите Alembic так, чтобы чистая database создавалась только из revision history.',
       'steps': ['Установите Alembic в project environment и выполните alembic init alembic.',
                 'Перенесите DATABASE_URL из settings в Alembic configuration без публикации secrets.',
                 'В alembic/env.py импортируйте Base и все ORM models.',
                 'Установите target_metadata = Base.metadata.',
                 'Создайте revision с autogenerate для tasks и categories.',
                 'Откройте revision и вручную проверьте upgrade и downgrade.',
                 'Удалите только disposable test database.',
                 'Выполните alembic upgrade head.',
                 'Проверьте alembic current, alembic history и таблицу alembic_version.',
                 'Через SQLite viewer подтвердите tables, columns, indexes и foreign key.',
                 'Добавьте integration test, который поднимает пустую database через upgrade head.'],
       'result': 'Готово, если чистая database получает полную schema только через migrations, current указывает на '
                 'head, а revision находится в Git.'}],
    91: [{'title': 'Измените schema отдельной revision',
       'task': 'Добавьте Task.description через новую migration. Старую revision изменять запрещено.',
       'steps': ['Добавьте description: Mapped[str | None] в ORM Task.',
                 'Добавьте description в TaskCreate, TaskUpdate и TaskRead как необязательное поле.',
                 'Создайте новую revision --autogenerate с названием add task description.',
                 'Проверьте, что upgrade добавляет nullable column, а downgrade удаляет только её.',
                 'Выполните upgrade head на development database.',
                 'Создайте и прочитайте задачу с description через API.',
                 'На disposable database выполните downgrade -1.',
                 'Проверьте отсутствие description через PRAGMA table_info(tasks).',
                 'Снова выполните upgrade head и повторите API-test.',
                 'Запустите весь pytest suite.'],
       'result': 'Готово, если schema меняется отдельной revision, upgrade и downgrade воспроизводимы, API '
                 'поддерживает description, а старые rows остаются валидными.'}],
    92: [{'title': 'Выпустите StudyHub Database API',
       'task': 'Проведите финальную приёмку четвёртого курса. Новые возможности не добавляются: проверяются '
               'воспроизводимость, database contract и документация.',
       'steps': ['Клонируйте проект в новую временную директорию либо используйте чистую копию repository.',
                 'Создайте virtual environment и установите зависимости только по README.',
                 'Создайте .env по .env.example.',
                 'Выполните alembic upgrade head на пустой database.',
                 'Запустите API командой из README.',
                 'Через Postman или Swagger создайте Category и две Task.',
                 'Получите list с фильтрами, sorting, limit и offset.',
                 'Обновите одну Task и удалите другую.',
                 'Спровоцируйте duplicate slug и проверьте 409, затем выполните корректный POST.',
                 'Получите Category с tasks и проверьте отсутствие N+1 regression.',
                 'Запустите pytest -q два раза подряд.',
                 'Обновите README: архитектура, settings, migrations, запуск, endpoints, tests и reset development '
                 'database.',
                 'Добавьте docs/release-check-stage4.md с фактическими командами и результатами.',
                 'Проверьте git status и создайте commit release: StudyHub Database API.',
                 'Создайте tag v2.0.0 и GitHub Release с кратким demo-сценарием.'],
       'result': 'Готово, если чистая установка создаёт schema через Alembic, полный API-сценарий проходит, conflict '
                 'не ломает Session, tests зелёные, README воспроизводим, а release v2.0.0 опубликован.'}]
}
