from typing import Any

MANUAL_PRACTICE: dict[int, list[dict[str, Any]]] = {
    208: [{'title': 'Проведите security и performance audit',
        'task': 'Проверьте StudyHub по конкретному checklist, найдите минимум три реальные проблемы и исправьте '
                'каждую отдельным доказуемым изменением.',
        'steps': ['Создайте docs/final-audit.md с колонками risk, evidence, severity, fix и verification.',
                  'Проверьте repository и image на secrets, .env, tokens и passwords.',
                  'Проверьте password/token handling и отсутствие sensitive data в logs.',
                  'Проверьте permissions matrix и object ownership для Course, Enrollment и Completion.',
                  'Проверьте CORS и production origins.',
                  'Проверьте parameterized SQL и отсутствие client-controlled owner_id/student_id.',
                  'Посчитайте SQL statements catalog, course structure и progress.',
                  'Проверьте N+1, indexes и EXPLAIN для двух ключевых queries.',
                  'Проверьте длину transactions и порядок commit → cache invalidation.',
                  'Проверьте rate limit fail-open/fail-closed policy.',
                  'Найдите минимум три подтверждённые проблемы.',
                  'Исправьте каждую отдельным commit с before/after test, plan или log.',
                  'Не называйте audit security certification или production readiness.'],
        'result': 'Готово, если минимум три риска имеют evidence, отдельные fixes и автоматическую либо измеримую '
                  'проверку, а оставшиеся ограничения честно записаны.'}],
    209: [{'title': 'Соберите risk-based test suite и release gate',
        'task': 'Закройте главные риски проекта автоматическими tests. Цель — стабильные контракты, а не '
                'максимальный процент coverage.',
        'steps': ['Создайте docs/final-test-matrix.md с колонками risk, test level, scenario и expected result.',
                  'Выделите unit tests domain rules, integration tests PostgreSQL/Redis и end-to-end LMS flow.',
                  'Добавьте auth и permissions matrix cases.',
                  'Добавьте transaction rollback для reorder, enrollment и completion.',
                  'Добавьте clean Alembic upgrade на новую PostgreSQL database.',
                  'Добавьте cache hit/miss/invalidation/Redis unavailable.',
                  'Добавьте BackgroundTasks test и external HTTP mock, если integration существует.',
                  'Уберите реальные sleep, external network и зависимость от порядка tests.',
                  'Запустите pytest с random order либо несколько раз в разном порядке.',
                  'Добавьте CI jobs quality, migrations, integration и image build.',
                  'Сломайте один critical contract и докажите red gate.',
                  'Верните fix и добейтесь полного green pipeline два раза подряд.'],
        'result': 'Готово, если release блокируется при нарушении auth, migration, transaction, cache или LMS flow, '
                  'tests детерминированы, а CI дважды проходит на чистых services.'}],
    210: [{'title': 'Перепишите README для recruiter, reviewer и developer',
        'task': 'Сделайте repository понятным без устного сопровождения. README должен объяснять продукт, решения и '
                'запуск, но не превращаться в учебник по всему стеку.',
        'steps': ['Начните README с проблемы и одного предложения о StudyHub LMS Release.',
                  'Добавьте роли student, teacher, admin и короткий список возможностей.',
                  'Добавьте architecture overview с FastAPI, PostgreSQL, Redis, Docker и CI и причинами выбора.',
                  'Добавьте актуальную ER-диаграмму Course, Module, Lesson, Enrollment и Completion.',
                  'Добавьте request flow teacher publish и student progress.',
                  'Добавьте quick start через Compose из чистого clone.',
                  'Опишите environment variables без real secret values.',
                  'Добавьте migrations, tests, CI и deployment commands.',
                  'Добавьте demo accounts или безопасный seed flow.',
                  'Добавьте curl/Postman examples основного LMS flow.',
                  'Добавьте trade-offs, known limitations и out-of-scope.',
                  'Попросите другого разработчика пройти quick start и исправьте найденные gaps.'],
        'result': 'Готово, если recruiter понимает ценность, reviewer видит решения и риски, developer запускает '
                  'project по README без сообщения автору.'}],
    211: [{'title': 'Пройдите 90-минутный interview lab',
        'task': 'Решите ограниченный набор задач без подсказок проекта и объясняйте ход решения. Оценивается '
                'процесс: уточнить, предложить, проверить и объяснить.',
        'steps': ['Подготовьте отдельный clean branch interview-lab и таймер на 90 минут.',
                  'Задача 1, 15 минут: прочитайте Python function и найдите один логический defect.',
                  'Задача 2, 15 минут: по traceback или log найдите причину failed request.',
                  'Задача 3, 15 минут: допишите небольшой FastAPI endpoint с validation и 404.',
                  'Задача 4, 15 минут: напишите SQL SELECT с JOIN, filter и stable ORDER BY.',
                  'Задача 5, 15 минут: добавьте pytest на ошибочный scenario.',
                  'Задача 6, 15 минут: проведите code review небольшого diff и оставьте минимум три замечания.',
                  'Перед каждой задачей вслух сформулируйте inputs, expected result и edge cases.',
                  'После каждой задачи запустите минимальную проверку.',
                  'Сохраните решения, время, ошибки и исправления в docs/interview-lab.md.',
                  'Повторите два самых слабых задания без таймера после разбора.'],
        'result': 'Готово, если за 90 минут получены проверяемые partial или complete решения, каждое решение '
                  'объяснено, а слабые места превращены в конкретный план повторения.'}],
    212: [{'title': 'Выпустите и защитите StudyHub LMS Release',
        'task': 'Проведите финальную приёмку из чистого окружения, опубликуйте versioned release и защитите '
                'архитектурные решения без чтения готового текста.',
        'steps': ['Клонируйте repository в новую временную директорию.',
                  'Создайте production-like configuration вне Git.',
                  'Поднимите PostgreSQL и Redis, примените Alembic upgrade head.',
                  'Разверните конкретный image tag и сохраните image digest.',
                  'Проверьте health, readiness, logs и CI commit status.',
                  'Выполните demo teacher: create Course, add content, publish.',
                  'Выполните demo student: catalog, enrollment, completion, progress 100%.',
                  'Покажите forbidden action чужого teacher и 429 rate limit.',
                  'Покажите cache miss, cache hit и invalidation after update.',
                  'Покажите background notification и controlled failure log.',
                  'Воспроизведите один smoke failure и rollback на known-good tag.',
                  'Запустите полный test suite два раза.',
                  'Обновите release notes, architecture diagrams и final audit.',
                  'Создайте commit release: StudyHub LMS Release и tag v7.0.0.',
                  'Опубликуйте GitHub Release с demo script, limitations и setup.',
                  'Проведите 10–15 минутную защиту: domain, auth, SQL, async, Docker, Redis, tests и trade-offs.',
                  'Составьте личный план следующих 8–12 недель по откликам, повторению и улучшению портфолио.'],
        'result': 'Готово, если clean deployment воспроизводим, полный LMS flow и failure paths показаны, release '
                  'связан с commit/image/migration, а ученик объясняет решения и ограничения без подсказки.'}]
}
